ai-plugin:
  schema-version: v1
  name-for-human: Tokyo OpenData
  name-for-model: tokyo_opendata
  description-for-human: Search for OpenData in Tokyo, using the Tokyo OpenData Catalog Site.
  description-for-model: Search for OpenData in Tokyo. Do not falsify open data when there is no corresponding data in the search results. Answer in the language asked. If you ask a question in a language other than Japanese, you must translate it into the language asking and not display Hiragana, Katakata, or Kanji. Use titleEn instead of title if entered in non-Japanese. Should show first user's search condition. Next, should show 'totalOfHits'. Finally, show 'showMoreUrl'. Must not generate your own parameters when not found among the options of organization, category, format.
  auth:
    type: none
  api:
    type: openapi
