ai-plugin:
  api:
    url: https://tokyo-opendata-chatgpt-plugin.fooqoo56.com/openapi.json
  logo-url: https://tokyo-opendata.s3.amazonaws.com/logo.png
  contact-email: fooqoofooqoo56@gmail.com
  legal-info-url: https://tokyo-opendata-chatgpt-plugin.fooqoo56.com/term-of-use
