ai-plugin:
  schema-version: v1
  name-for-human: Tokyo OpenData
  name-for-model: tokyo_opendata
  description-for-human: Search for OpenData in Tokyo. This plugin is in beta.
  description-for-model: Search for OpenData in Tokyo. Do not falsify open data when there is no corresponding data in the search results. Should show first user's search condition. Next, should show 'totalOfHits'. Finally, show 'showMoreUrl'. Must not generate your own parameters when not found among the options of organization, category, format.
  auth:
    type: none
  api:
    type: openapi
